In [2]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import  numpy as np
n = np.zeros(10)
n[4]=1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
#2. Create a vector with values ranging from 10 to 49.

n = np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#3.Create a 3x3 matrix with values ranging from 0 to 8
n = np.arange(0,9)

In [5]:
n.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# 4.Find indices of non-zero elements from [1,2,0,0,4,0]
n = np.nonzero([1,2,0,0,4,0])
n

(array([0, 1, 4], dtype=int32),)

In [13]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
n = np.random.rand(10,10)
min = n.min()
max = n.max()
print("min:",min)
print("max:",max)

min: 0.0038839908725395444
max: 0.9942418166430381


In [14]:
#6. Create a random vector of size 30 and find the mean value.
n = np.random.rand(30)
m = n.mean()
m

0.4308756235471472